---
fail_fast: true

repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: python
        require_serial: true
        types: [python]

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: python
        require_serial: true
        types: [python]

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [python]

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        # https://github.com/pre-commit/pre-commit/issues/1129
        entry: env PYTHONPATH=. pylint
        language: python
        types: [python]
        args: [--score=n]
        exclude: ^tests/

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy .
        language: python
        types: [python]
        pass_filenames: false
        always_run: true

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3
    hooks:
      - id: yamllint
