"""
This one takes csv file generated by MakeSense.ai and converts it to json
suitable for this task
"""
import argparse
import csv
import json
import warnings
from pathlib import Path


def main(
    csv_file: str,
    images_folder: str,
) -> None:
    images_folder = Path(images_folder)
    with open(csv_file) as file:
        reader = csv.DictReader(file)
        for row in reader:
            image = images_folder / row["image_name"]
            if not image.exists():
                warnings.warn(f"Image {image} does not exist. Skipping...")
                continue

            x, y, w, h = (
                float(row["bbox_x"]),
                float(row["bbox_y"]),
                float(row["bbox_width"]),
                float(row["bbox_height"]),
            )
            image_width, image_height = float(row["image_width"]), float(
                row["image_height"]
            )
            result = {
                "visible": 1,
                "bbox": [
                    y / image_height,
                    x / image_width,
                    (y + h) / image_height,
                    (x + w) / image_width,
                ],
            }

            dest_json_file = images_folder / f"{image.stem}.json"
            with open(dest_json_file, "w") as json_file:
                json_file.write(json.dumps(result))

    print("Converting finished!")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--csv",
        "-c",
        dest="csv_file",
        required=True,
    )
    parser.add_argument("--images", "-i", dest="images_folder", required=True)
    main(**vars(parser.parse_args()))
